#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

if [ ! -f ./bin/bindown ]; then
  mkdir -p ./bin
  sh -c "$(curl -sfL https://github.com/WillAbides/bindown/releases/download/v3.7.8/bootstrap-bindown.sh)"
fi

exec bin/bindown "$@"
