#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

script/bindown install -q yq

output() {
  templates="$(yq '.templates | keys | .[]' bindown.yml)"
  for template in $templates; do
    homepage="$(yq ".templates.$template.homepage" bindown.yml)"
    description="$(yq ".templates.$template.description" bindown.yml)"
    if [ "$description" = "null" ]; then
      description=""
    else
      description=" - $description"
    fi
    if [ "$homepage" != "null" ]; then
      template="[$template]($homepage)"
    fi
    echo "- $template$description"
  done
}

usage_pattern="<!--- start usage output --->*<!--- end usage output --->"

usag_sub="$(cat <<EOF
<!--- start usage output --->
$(output)
<!--- end usage output --->
EOF
)"

readme="$(cat README.md)"
echo "${readme//$usage_pattern/$usag_sub}" > README.md
