on:
  push:
  workflow_dispatch:

name: ci

jobs:
  validate-all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: script/validate-all
      - run: script/generate --check
      - if: github.ref == 'refs/heads/main'
        run: script/release
