on:
  push:
  workflow_dispatch:

name: ci

jobs:
  validate-all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: script/validate-all
      - run: script/generate --check
